export const DEFAULT_TITLE = 'Metal Radio Playlist'
export const DEFAULT_HOME_URL = 'https://x.changwoo.pe.kr/rapl-front'
export const DEFAULT_API_URL = 'https://x.changwoo.pe.kr/rapl'
export const DEFAULT_BLOG_URL = 'https://blog.changwoo.pe.kr'
export const DEFAULT_MCPL_URL = 'https://x.changwoo.pe.kr/rapl/music-camp'
